os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python3 -m pyster.init --project_path samples/foobar --module_name foobar.foobar
  - python3 -m pyster.gen --project_path samples/foobar --module_name foobar.foobar -c 50 -t 1
  - python3 -m pyster --project_path samples/foobar --module_name foobar.foobar -c 50 -t 1
