os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pytest tests/test*

after_success:
  - pip install coveralls
  - coverage run --source=mypkg -m pytest tests/
  - coveralls
